{% set name = "pyglotaran-extras" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyglotaran_extras-{{ version }}.tar.gz
  sha256: 114b5a818f12ce3db53d4dcd6cfc15fb1770acc84cded88105a0ae68050ec63f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - matplotlib-base >=3.3.0
    - pyglotaran >=0.5.0
    - python >=3.8,<3.11
    - xarray >=2022.3.0

test:
  imports:
    - pyglotaran_extras
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/glotaran/pyglotaran-extras
  summary: Supplementary package for pyglotaran with (example) plotting code.
  dev_url: https://github.com/glotaran/pyglotaran-extras
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
    - jsnel
