{% set python_min = "3.10" %}
{% set name = "pyglotaran-extras" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyglotaran_extras-{{ version }}.tar.gz
  sha256: 3da48ac3251aebed82e66d3bd162cbd3fce40d6763e1d38c3ffe9766456d4523

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - cycler >=0.10
    - docstring_parser >=0.16
    - matplotlib-base >=3.3.0
    - numpy >=1.22
    - pydantic >=2.7
    - pyglotaran >=0.7.0
    - ruamel.yaml >=0.18.6
    - python >={{ python_min }}
    - tabulate >=0.8.9
    - xarray >=2022.3.0

test:
  imports:
    - pyglotaran_extras
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/glotaran/pyglotaran-extras
  summary: Supplementary package for pyglotaran with (example) plotting code.
  dev_url: https://github.com/glotaran/pyglotaran-extras
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
    - jsnel
