{% set name = "pyglotaran-extras" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyglotaran_extras-{{ version }}.tar.gz
  sha256: 6aee6400d6a1662c8dfde461d746cc8a4d72e3cfa2c71ed93ee14dd1ac91d61e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - cycler >=0.10
    - matplotlib-base >=3.3.0
    - numpy >=1.21.2,<1.24
    - pyglotaran >=0.6.0
    - python >=3.8,<3.11
    - tabulate >=0.8.9
    - xarray >=2022.3.0

test:
  imports:
    - pyglotaran_extras
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/glotaran/pyglotaran-extras
  summary: Supplementary package for pyglotaran with (example) plotting code.
  dev_url: https://github.com/glotaran/pyglotaran-extras
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
    - jsnel
